# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-19 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('content', models.CharField(max_length=1000, null=True)),
                ('status', models.IntegerField(max_length=1, null=True)),
                ('crUserid', models.BigIntegerField(max_length=20, null=True)),
                ('crTime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tb_meeting',
            },
        ),
    ]
